import sys
Geograpy = int(sys.argv[1])
Credit_Score = int(sys.argv[2])
Gender = int(sys.argv[3])
Age = int(sys.argv[4])
Tenure = int(sys.argv[5])
Balance = int(sys.argv[6])
Products = int(sys.argv[7])
CreditCard = int(sys.argv[8])
Member = int(sys.argv[9])
Salary = int(sys.argv[10])
print(Salary)
sys.stdout.flush()